config/routes.rb
Smsgateway::Application.routes.draw do
  resources :users do
     post 'send_sms' ,:on=>:collection
  end
  root :to => "users#index"
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :mobile_number, :address, :city, :state
  validates :name, :email, :mobile_number, :address, :city, :state ,:presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ######## For SMS Gateway ##############
  require 'net/http'
  require 'uri'
  ####################################
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, :notice => "Successfully destroyed user."
  end

  def send_sms
    @mobile_numbers = User.find(params[:user_ids]).map(&:mobile_number)
    message = "Hi this is test sms"
    url = "http://voice.full2ads.co.cc/api/sms.php?uid=6368616974616e7961&pin=4e4ce8b0a500c&sender=SARKCSC&route=1&mobile=#{@mobile_numbers.join(',')}&message=#{message}"
    Net::HTTP.get_print URI.parse(URI.encode(url.strip))
    redirect_to users_path,:notice => 'Sms send successfully...'
  end

=begin
  def sms_status
    mobile = @pancard.mobile
    #name = @pancard.first_name + @pancard.last_name
    message = "Dear Customer,Received amount of Rs."+@pancard.amount.to_s+"/- towards PAN Application.Your Reference No: "+@pancard.panapplication_number+"."
    url = "http://voice.full2ads.co.cc/api/sms.php?uid=6368616974616e7961&pin=4e4ce8b0a500c&sender=SARKCSC&route=1&mobile=#{mobile},9666138888&message=#{message}"
    Net::HTTP.get_print URI.parse(URI.encode(url.strip))
  end
=end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_all
    "<input type='checkbox' name='checkall' id='checkall'/>".html_safe
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :mobile_number %><br />
    <%= f.text_field :mobile_number %>
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @user %> |
  <%= link_to "View All", users_path %>
</p>

app/views/users/index.html.erb
<% title "Listing all users" %>
<% if @users.blank? %>
    <h3><i>There are no users yet</i></h3>
<% else %>
    <%= form_tag(send_sms_users_path) do %>
        <table id="main_table" class="tablesorter">
          <thead>
          <tr>
            <th><%= check_all %> check/uncheck</th>
            <th>Name</th>
            <th>Email</th>
            <th>Mobile Number</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% for user in @users %>
              <tr class="<%=cycle('even', 'odd')%>">
                <td><%= check_box_tag "user_ids[]", user.id,false,{:id=>"data_#{user.id}"} %></td>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.mobile_number %></td>
                <td><%= user.address %></td>
                <td><%= user.city %></td>
                <td><%= user.state %></td>
                <td><%= link_to "Show", user %> |
                  <%= link_to "Edit", edit_user_path(user) %> |
                  <%= link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %>
              </tr>
          <% end %>
          </tbody>
        </table>
        <div align="left"><%= submit_tag 'Send sms' %> </div>
    <% end %>
<% end %>

<p><%= link_to "Create New User", new_user_path %></p>

app/views/users/new.html.erb
<% title "New User" %>

<%= render 'form' %>

<p><%= link_to "Back to List", users_path %></p>

app/views/users/show.html.erb
<% title "User" %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Mobile Number:</strong>
  <%= @user.mobile_number %>
</p>
<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>
<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <%= link_to "Edit", edit_user_path(@user) %> |
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>